# -*- coding: utf-8 -*-
"""Codigos estables de los errores del ledger temporal.

Cada constante nombra una CONDUCTA, no un mensaje. Renombrar el texto de una
excepcion no toca su codigo; cambiar el codigo es un cambio de contrato y debe
razonarse en el PR.
"""
from __future__ import annotations


class LedgerCodes:
    # --- almacen y serializacion de entradas -------------------------------
    STORE_SEQ_OUT_OF_ORDER = "LEDGER_STORE_SEQ_OUT_OF_ORDER"
    STORE_LINE_UNREADABLE = "LEDGER_STORE_LINE_UNREADABLE"
    ENTRY_UNKNOWN_FIELDS = "LEDGER_ENTRY_UNKNOWN_FIELDS"
    ENTRY_MISSING_FIELDS = "LEDGER_ENTRY_MISSING_FIELDS"

    # --- integridad de la cadena de custodia (append-only) ------------------
    CHAIN_SEQ_GAP = "LEDGER_CHAIN_SEQ_GAP"
    CHAIN_PREV_HASH_BROKEN = "LEDGER_CHAIN_PREV_HASH_BROKEN"
    ENTRY_HASH_MISMATCH = "LEDGER_ENTRY_HASH_MISMATCH"
    RECORDED_AT_REGRESSION = "LEDGER_RECORDED_AT_REGRESSION"
    REVISION_MISMATCH = "LEDGER_REVISION_MISMATCH"
    ASSERTION_ID_MISMATCH = "LEDGER_ASSERTION_ID_MISMATCH"
    RECORDED_AT_DOC_MISMATCH = "LEDGER_RECORDED_AT_DOC_MISMATCH"
    IMPOSSIBLE_HISTORY = "LEDGER_IMPOSSIBLE_HISTORY"
    WORKSPACE_LEAK = "LEDGER_WORKSPACE_LEAK"

    # --- identidad y unicidad ----------------------------------------------
    ASSERTION_ALREADY_EXISTS = "LEDGER_ASSERTION_ALREADY_EXISTS"
    DUPLICATE_LOGICAL_IDENTITY = "LEDGER_DUPLICATE_LOGICAL_IDENTITY"
    UNKNOWN_ASSERTION = "LEDGER_UNKNOWN_ASSERTION"
    BAD_ASSERTION_TYPE = "LEDGER_BAD_ASSERTION_TYPE"

    # --- tiempo -------------------------------------------------------------
    RECORDED_AT_INVALID = "LEDGER_RECORDED_AT_INVALID"
    MONOTONIC_VIOLATION = "LEDGER_MONOTONIC_VIOLATION"
    AS_OF_INVALID = "LEDGER_AS_OF_INVALID"

    # --- ciclo de vida -------------------------------------------------------
    BIRTH_STATUS_INVALID = "LEDGER_BIRTH_STATUS_INVALID"
    BORN_SUPERSEDED = "LEDGER_BORN_SUPERSEDED"
    CONFIRM_ON_PLANNED = "LEDGER_CONFIRM_ON_PLANNED"
    CONFIRM_WITHOUT_NEW_EVIDENCE = "LEDGER_CONFIRM_WITHOUT_NEW_EVIDENCE"
    CONFIRM_LOWERS_CONFIDENCE = "LEDGER_CONFIRM_LOWERS_CONFIDENCE"
    SELF_CONTRADICTION = "LEDGER_SELF_CONTRADICTION"

    # --- supersesion ---------------------------------------------------------
    SUPERSEDE_REUSES_ID = "LEDGER_SUPERSEDE_REUSES_ID"
    SUPERSEDE_TARGET_EXISTS = "LEDGER_SUPERSEDE_TARGET_EXISTS"
    SUPERSEDE_NOT_FORWARD = "LEDGER_SUPERSEDE_NOT_FORWARD"
    SUPERSESSION_CYCLE = "LEDGER_SUPERSESSION_CYCLE"
    VALIDITY_ALREADY_CLOSED = "LEDGER_VALIDITY_ALREADY_CLOSED"
    VALIDITY_MISSING_VALID_TO = "LEDGER_VALIDITY_MISSING_VALID_TO"
    VALIDITY_INVERTED = "LEDGER_VALIDITY_INVERTED"

    # --- transiciones y motivos ----------------------------------------------
    UNKNOWN_STATUS = "LEDGER_UNKNOWN_STATUS"
    UNKNOWN_SOURCE_STATUS = "LEDGER_UNKNOWN_SOURCE_STATUS"
    ILLEGAL_TRANSITION = "LEDGER_ILLEGAL_TRANSITION"
    REASON_CODE_INVALID = "LEDGER_REASON_CODE_INVALID"


__all__ = ["LedgerCodes"]
