# -*- coding: utf-8 -*-
"""Codigos estables de los errores criticos del writer seguro y de la
supersesion revisada.

Mismo contrato que `knowledge_v3/ledger/codes.py`: el codigo nombra la conducta
(que garantia RC se ha defendido), nunca el mensaje. Ver `coded_errors`.
"""
from __future__ import annotations


class WriterCodes:
    """Garantia RC: el writer NO escribe salvo en el camino autorizado."""

    DRY_RUN_VIOLATION = "WRITER_DRY_RUN_VIOLATION"
    REAL_INGEST_NOT_AUTHORIZED = "WRITER_REAL_INGEST_NOT_AUTHORIZED"
    NEO4J_UNAVAILABLE = "WRITER_NEO4J_UNAVAILABLE"
    PREFLIGHT_UNSAFE = "WRITER_PREFLIGHT_UNSAFE"
    CONFLICT_EXISTING_NODE = "WRITER_CONFLICT_EXISTING_NODE"
    USE_EXISTING_NOT_FOUND = "WRITER_USE_EXISTING_NOT_FOUND"
    USE_EXISTING_AMBIGUOUS = "WRITER_USE_EXISTING_AMBIGUOUS"
    LABEL_NOT_ALLOWED = "WRITER_LABEL_NOT_ALLOWED"
    RELATIONS_NOT_ALLOWED = "WRITER_RELATIONS_NOT_ALLOWED"
    CONFLICTING_REVIEW_REPORT = "WRITER_CONFLICTING_REVIEW_REPORT"
    PACKAGE_REJECTED = "WRITER_PACKAGE_REJECTED"
    PROVENANCE_REJECTED = "WRITER_PROVENANCE_REJECTED"
    WRITE_PROVENANCE_INCOMPLETE = "WRITER_WRITE_PROVENANCE_INCOMPLETE"
    RELATION_SOURCE_KIND_MISSING = "WRITER_RELATION_SOURCE_KIND_MISSING"
    RELATION_REVIEW_STATUS_MISSING = "WRITER_RELATION_REVIEW_STATUS_MISSING"
    ROLLBACK_BATCH_ID_EMPTY = "WRITER_ROLLBACK_BATCH_ID_EMPTY"
    REPORT_NOT_FOUND = "WRITER_REPORT_NOT_FOUND"


#: Codigos de hallazgo del preflight. NO son excepciones: viajan en
#: `rep["error_codes"]` para que un test pueda afirmar QUE detecto el preflight
#: sin leer la redaccion de `rep["errors"]`.
class PreflightFindings:
    CONFLICT_EXISTING_NODE = "PREFLIGHT_CONFLICT_EXISTING_NODE"
    AMBIGUOUS_EXISTING_NODES = "PREFLIGHT_AMBIGUOUS_EXISTING_NODES"
    USE_EXISTING_NOT_FOUND = "PREFLIGHT_USE_EXISTING_NOT_FOUND"
    USE_EXISTING_AMBIGUOUS = "PREFLIGHT_USE_EXISTING_AMBIGUOUS"


class SupersedeCodes:
    """Garantia RC: la supersesion revisada es fail-closed."""

    INPUT_NOT_FOUND = "SUPERSEDE_INPUT_NOT_FOUND"
    IN_OUT_SAME_FILE = "SUPERSEDE_IN_OUT_SAME_FILE"
    OUTPUT_EXISTS = "SUPERSEDE_OUTPUT_EXISTS"
    ALREADY_SUPERSEDED = "SUPERSEDE_ALREADY_SUPERSEDED"
    INVALID_JSON = "SUPERSEDE_INVALID_JSON"
    SCHEMA_INVALID_INPUT = "SUPERSEDE_SCHEMA_INVALID_INPUT"
    SCHEMA_INVALID_OUTPUT = "SUPERSEDE_SCHEMA_INVALID_OUTPUT"
    NOT_AN_EXISTING_MATCH = "SUPERSEDE_NOT_AN_EXISTING_MATCH"
    CHECKSUM_MISMATCH = "SUPERSEDE_CHECKSUM_MISMATCH"
    AUDIT_FAILED = "SUPERSEDE_AUDIT_FAILED"
    SOURCE_MODIFIED_DURING = "SUPERSEDE_SOURCE_MODIFIED_DURING"
    SOURCE_MODIFIED_AFTER = "SUPERSEDE_SOURCE_MODIFIED_AFTER"
    WRITTEN_SHA_MISMATCH = "SUPERSEDE_WRITTEN_SHA_MISMATCH"
    FIELD_REQUIRED = "SUPERSEDE_FIELD_REQUIRED"
    FIELD_DANGEROUS_UNICODE = "SUPERSEDE_FIELD_DANGEROUS_UNICODE"
    PATH_TRAVERSAL = "SUPERSEDE_PATH_TRAVERSAL"
    PATH_SYMLINK = "SUPERSEDE_PATH_SYMLINK"


__all__ = ["PreflightFindings", "SupersedeCodes", "WriterCodes"]
